### ISSUE TITLE
readings

### ISSUE THREAD

**Issue by jiale0402** [jiale0402/features#1]
1. read https://www.coinbase.com/learn/advanced-trading/what-is-an-order-book
2. read https://www.coinbase.com/learn/crypto-basics/what-are-technical-analysis-and-fundamental-analysis
3. read https://arxiv.org/ftp/arxiv/papers/1601/1601.00991.pdf

**Comment by jiale0402** [comment]
always lmk if u encounter any questions, u can follow up in this issue or just email me

**Comment by abm312** [comment]
gotcha

**Comment by jiale0402** [comment]
just to add some more to the reading so that u have an idea:
reading 1 is to introduce u what is an orderbook and why do we want to extract meaningful infromation from it. This is more on the background or required knowledge side of stuff (we won't require this anytime soon but it's really really important to understand what this is).
reading 2 is a very simple and popular way of feature engineering financial data. at the end of the day feature engineering is the art of extracting meaningful information with domain expertise so our models can learn stuff better.
reading 3 is about what we do. make sure u finish 1 and 2 before approaching 3. Consult https://en.wikipedia.org/wiki/Open-high-low-close_chart or any other resource u need if u find any unfamiliar term.

happy learning @abm312

**Comment by jiale0402** [comment]
oh and sorry I didn't bring this up earlier. It's more important to learn how to use github, once you finish the reading you can start by making a pull request that adds some more content (just say sth like u finished the reading) into the readme of the repo and assign the review of the PR to me (this is to get u familiarized with the future workflow) @abm312 

and never directly push anything to the main branch ever!

**Comment by abm312** [comment]
@jiale0402 
Can you take a look at reading #2
It only distinguishes b/w technical and fundamental analysis and has no mention of feature engineering and the stuff you mention above, I think I might have the wrong link.


2. read https://www.coinbase.com/learn/crypto-basics/what-are-technical-analysis-and-fundamental-analysis

**Comment by jiale0402** [comment]
> @jiale0402 Can you take a look at reading #2 It only distinguishes b/w technical and fundamental analysis and has no mention of feature engineering and the stuff you mention above, I think I might have the wrong link.
> 
> 2. read https://www.coinbase.com/learn/crypto-basics/what-are-technical-analysis-and-fundamental-analysis

Both fundamental analysis and technical analysis are ways of feature engineering. At the end of the day, feature engineering is just trying to turn information into numbers such that we can model better. 
https://www.investopedia.com/terms/t/technicalanalysis.asp#:~:text=Technical%20analysis%20is%20a%20trading,as%20price%20movement%20and%20volume.
You can take a brief look at this article. These analysis tools offer a simple way of modelling the data, these technical indicators can be features as well.

**Comment by abm312** [comment]
Thank you for clarifying that.
I learned how to navigate github, and created a pull request, let me know if my procedure was standard.
I went through the readings in full. They were very interesting especially the third one. Do you suggest, I spend the time learning how this calculation in it in depth as I feel like it just skimmed over this part(and any book/course recommendations for this type of math?)
<img width="278" alt="Screenshot 2023-11-24 at 12 48 23 AM" src="https://github.com/jiale0402/features/assets/127000559/6e04b2a3-4777-408e-b197-4253c5c31661">

**Comment by abm312** [comment]
Also @jiale0402  I was also looking into learning numpy and pandas, is there any standard resources out there for it?
I landed on this free course by Georgia Tech: https://www.udacity.com/course/machine-learning-for-trading--ud501

Do you think this is a good starting point?

**Comment by jiale0402** [comment]
> Thank you for clarifying that. I learned how to navigate github, and created a pull request, let me know if my procedure was standard. I went through the readings in full. They were very interesting especially the third one. Do you suggest, I spend the time learning how this calculation in it in depth as I feel like it just skimmed over this part(and any book/course recommendations for this type of math?) <img alt="Screenshot 2023-11-24 at 12 48 23 AM" width="278" src="https://private-user-images.githubusercontent.com/127000559/285380086-6e04b2a3-4777-408e-b197-4253c5c31661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4ODIyMDQsIm5iZiI6MTcwMDg4MTkwNCwicGF0aCI6Ii8xMjcwMDA1NTkvMjg1MzgwMDg2LTZlMDRiMmEzLTQ3NzctNDA4ZS1iMTk3LTQyNTNjNWMzMTY2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwMzExNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2Y5Yzk5ODRiZGIzMTljMjNmNTliNDFmODdlZTk4NzE5NjlhYmQ2NzRhMDVhZjVjNGQ2ZWY5NjQzODg3YTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qeMjcykwO8Bj4zkGCHyXeRAbPdm-eAQtpe50_yY1vHk">

Great you liked it. You will have to go in depth for a few of those soon because your next task would be implementing some of the alphas mentioned in the third reading material lol

regarding learning numpy and stuff: my personal favorite way is just roll with whatever u have, and if you encounter any difficulty, use numpy's official doc and stackoverflow to find a solution for your problem. but it's up to you to do that course or not, at the end of the day the goal is making u to be ready for utilizing numpy in your code so whatever works

**Comment by jiale0402** [comment]
after you finish up one assignment you may close the issue here (use the close with comment option and attach the exact pr that handles this issue) @abm312

**Comment by abm312** [comment]
This issue has been resolved with the changes in PR #2.

**Comment by abm312** [comment]
This issue has been resolved with the changes in PR #2.
