### ISSUE TITLE
learn numpy & re-read alpha 101

### ISSUE THREAD

**Issue by jiale0402** [jiale0402/features#3]
this time I would like you to make sense of the alphas mentioned in the WorldQuant Alpha 101 paper. 
Please select 5 alphs that you think you can understand (in terms of what exact phenominum/pattern is this alpha categorizing) and summarize what they represent in a markdown file, the upload it to github

additionally, mention what numpy function could be useful for computing this alpha assuming you will do it (which u will soon)

**Comment by jiale0402** [comment]
sry for being late :(

**Comment by abm312** [comment]
Thank you!
I'm wrapping up finals right now and will be travelling a bit right after so my turnaround for this will be a little longer. Enjoy your break and have a great day!

**Comment by abm312** [comment]
Hi @jiale0402 , happy new year! 
I learned numpy basics and went through the alphas thoroughly and wrote my summarization alongwith the numpy/pandas functions I thought would be applicable in a markdown file which I pushed to the repo. I think I accidentally pushed it to master too, just to confirm, that's something I should avoid right?

**Comment by jiale0402** [comment]
Good works! I will check out your summarization. But before that, you are absolutely correct that this should avoided. Please ensure that you never directly push to the main branch.

As a side practice, here are 2 new assignments for you:
1. set up branch protection such that no commits can be directly pushed to the master branch
2. revert your push to the master branch and make a pr that contains the work you've done over the break.

We might welcome one or two new members this quarter, would you be willing to share this repo to the new comers? Because I think it contains many useful information and others might learn from your path of learning. 

Happy new year! @abm312

**Comment by abm312** [comment]
Yes, I'm more than happy to share this repo with others to aid their learning process.
I created a PR for the work over break summary. I also reverted the push I did to master, and I'm trying to setup branch protection like you asked but I think it can't be done w/o admin access in this repo as I don't see a settings tab on my end. @jiale0402 


<img width="1307" alt="Screenshot 2024-01-02 at 8 25 33 PM" src="https://github.com/jiale0402/features/assets/127000559/1d8b7b62-e62c-4000-ace3-2ef3116016ad">

**Comment by jiale0402** [comment]
Oh that's a mistake on my part. Sorry about that. I just added the branch protection rule.

Going forwards, I will start to assign coding works as you have familiarized yourself with the necessary libraries. 

Right now I will need a couple days to discuss with professor Wang about what needs to be done first during the quarter. After we nail down a direction, I will distribute tasks according to priority.

Thanks for your participation thus far! And by the way, would you be willing to collaborate with a new member on the tasks that I will assign in the future or do you prefer working alone?

**Comment by abm312** [comment]
@jiale0402 
Yep I'm open to having a partner to collaborate with.
Looking forward to it!
